#!/usr/bin/env bash

# install with
# sudo cp tookie-osint /usr/local/bin/ 
# sudo chmod +x /usr/local/bin/tookie-osint   
#
# Directory of tookie-osint script
SCRIPT_DIR="/home/alfredredbird/CODE/tookie-osint"
VENV_DIR="$SCRIPT_DIR/.venv"

# Create virtual environment if none
if [ ! -d "$VENV_DIR" ]; then
    python3 -m venv "$VENV_DIR"
    "$VENV_DIR/bin/pip" install --upgrade pip
    "$VENV_DIR/bin/pip" install -r "$SCRIPT_DIR/requirements.txt"
fi

# Activate venv and run the script
"$VENV_DIR/bin/python" "$SCRIPT_DIR/brib.py" "$@"
